framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            new_post:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: new_post
                        type: direct
                    queues:
                        new_post: ~
            friendship:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: friendships_exchange
                        type: direct
                    queues:
                        friendship: ~
