services:
  # PHP-FPM
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_network_php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - postgres-master
      - redis

  # Nginx
  nginx:
    image: nginx:latest
    container_name: social_network_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - php
    networks:
      - app-network

  # Redis
  redis:
    image: redis:latest
    container_name: social_network_redis
    volumes:
      - ./docker/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  # База данных (PostgreSQL)
  postgres-master:
    image: postgres:17
    container_name: social_network_postgres-master
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/postgres-master/data:/var/lib/postgresql/data
      - ./docker/postgres-master/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5434:5432"
    networks:
      - app-network

  # База данных (PostgreSQL)
  postgres-slave1:
    image: postgres:17
    container_name: social_network_postgres-slave1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/postgres-slave1/data:/var/lib/postgresql/data
      - ./docker/postgres-slave1/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5435:5432"
    networks:
      - app-network
    depends_on:
      postgres-master:
        condition: service_healthy

  # База данных (PostgreSQL)
  postgres-slave2:
    image: postgres:17
    container_name: social_network_postgres-slave2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/postgres-slave2/data:/var/lib/postgresql/data
      - ./docker/postgres-slave2/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5436:5432"
    networks:
      - app-network
    depends_on:
      postgres-master:
        condition: service_healthy

# Сеть для соединения контейнеров
networks:
  app-network:
    driver: bridge
